#!/bin/bash
#
# This script will install zsh within your home directory or within /usr/local/sbin
#

#--------------------
# Functions
#--------------------
install_method() {
	echo "Do you want to install system wide or home only? (s/h)"
	read INSTALL
}

clone_repository() { 
	echo -e "- Start Cloning repository into $1..."
	# wget https://raw.githubusercontent.com/jordantrizz/zsh/master/install
	git clone --recursive https://github.com/jordantrizz/zsh.git $1
	git submodule update --init --recursive
}


setup_home() {
	if ! [ -f $HOME."/.zshrc" ]; then
	       	ln -s $HOME/zsh/.zshrc ~/.
	       	clone_repository "$HOME/zsh"
	       	echo -e " - ZSH in-place, type zsh to start your shell\n"
	else
	       	echo -e " - There's already a .zshrc in-place, remove it and re-run\n"
	       	exit 1
	fi
}

setup_system() {
	# Confirm that /usr/local/sbin exists
	echo -e "Setting up system based .zshrc..."
	SYSTEM=/usr/local/sbin
	if ! [ -d "$SYSTEM/zsh" ]; then
		echo -e " - Cloning into $SYSTEM/zsh\n"
		clone_repository "$SYSTEM/zsh"
		echo "ZSH_ROOT=/usr/local/sbin/zsh" >> /etc/zsh/zshrc
		echo "source /usr/local/sbin/zsh/.zshrc" >> /etc/zsh/zshrc
	else
		echo -e " - $SYSTEM/zsh already exists\n"
		exit 1
	fi
	# Uncommented for now, need to review
	#echo -e " - Detecting OS and installing for all system users"
	#if [ -f /etc/debian_version ]; then
	#	echo -e " -- Detected Debian/Ubuntu OS"		
	#fi
	#echo "This is broken and needs to be fixed! and should probably be in /usr/share/zsh?"

}		

#--------------------
# Main Code
#--------------------

# Checking if zsh is installed
echo "Checking if zsh is installed...."
if ! [ -x "$(command -v zsh)" ]; then
        echo -e " - Error: zsh is not installed.\n"
        exit 1
else
        ZSH_SHELL=`which zsh`
        echo -e " - ZSH is installed in $ZSH_SHELL\n"
fi

# Check if zsh is the default shell
echo -e "Checking if zsh is the default shell"
if ! [[ $SHELL == *"zsh" ]]; then
        echo -e " - Your default shell isn't zsh, use chsh to change it to zsh.\n"
else
        echo -e " - ZSH is your default shell!\n"
fi

# Checking if git is installed
echo "Checking if git is installed...."
if ! [ -x "$(command -v git)" ]; then
        echo -e " - You need to install git!\n"
        exit 1
else
        echo -e " - GIT is installed!\n"
fi

# Start installtion
echo -e "---\n\nBegin Install\n"
install_method
if [ $INSTALL = "s" ]; then
        setup_system
elif [ $INSTALL = "h" ]; then
        setup_home
else
        install_method "Choose s or h on your keyboard"
fi
