#!/bin/bash
#
# This script will install zsh within your home directory or within /usr/local/sbin
#

#--------------------
# Functions
#--------------------

flight_check() {
	# Checking what package manager we have
	echo -n "Checking what package manager we have...."
	if [ -x "$(command -v apt)" ]; then
		echo "We have apt!"
		PKG_MANAGER="apt"
	elif [ -x "$(command -v yum)" ]; then
		echo "We have yum!"
		PKG_MANAGER="yum"
	fi
	
        # Checking if zsh is installed
        echo -n "Checking if zsh is installed...."
        if ! [ -x "$(command -v zsh)" ]; then
                echo -e "- Error: zsh is not installed."
                echo -e "- Trying to install via $PKG_MANAGER...."
                if [[ $PKG_MANAGER == "apt" ]]; then 
                	sudo apt-get install zsh
                	if [ $? -eq 1 ];then echo "zsh install failed....";exit 1; fi
                elif [[ $PKG_MANAGER == "yum" ]]; then 
                	sudo yum install zsh
			if [ $? -eq 1 ];then echo "zsh install failed....";exit 1; fi
        else
                ZSH_SHELL=`which zsh`
                echo -e "- ZSH is installed in $ZSH_SHELL"
        fi

        # Check if zsh is the default shell
        echo -n "Checking if zsh is the default shell...."
        if ! [[ $SHELL == *"zsh" ]]; then
                echo -e "- Your default shell isn't zsh, use chsh to change it to zsh."
        else
                echo -e "- ZSH is your default shell!"
        fi

        # Checking if git is installed
        echo -n "Checking if git is installed...."
        if ! [ -x "$(command -v git)" ]; then
                echo -e "- You need to install git!"
                exit 1
        else
                echo -e "- GIT is installed!"
        fi
}

install_method() {
        echo "Do you want to install system wide or home only? (s/h)"
        read INSTALL
        echo "(d)evelop or (m)aster Branch? (d/m)"
        read BRANCH
        echo "Include Ultimate Linux Toolbox? (y/n)"
        read ULTB
        echo "Include Ultimate WordPress Tools? (y/n)"
        read ULTB
}

clone_repository() {
        if ! [ -d $1 ];then
                echo -e "- Start Cloning repository into $1..."
                if [ $BRANCH = "d" ]; then
                        git clone --branch develop https://github.com/jordantrizz/zsh.git $1
			if [ $ULTB = "y" ]; then
				echo -e "- Installing ULTB $1"
				cd $1
                        	git submodule update --init --recursive
                        fi
                elif [ $BRANCH = "m" ]; then
                        git clone https://github.com/jordantrizz/zsh.git $1
			if [ $ULTB = "y" ]; then
				echo -e "- Installing ULTB $1"
				cd $1
                                git submodule update --init --recursive
                        fi
                fi
        else
                echo -e "- Directory $1 exists...exiting."
                exit 1
        fi
}

setup_home() {
	if ! [ -f $HOME/.zshrc ]; then
		clone_repository "$HOME/zsh"
	       	cp $HOME/zsh/.zshrc_install $HOME/.zshrc
	       	echo -e "- ZSH in-place, type zsh to start your shell\n"
	else
	       	echo -e "- There's already a .zshrc in-place, remove it and re-run\n"
	       	exit 1
	fi
}

setup_system() {
	# Confirm that /usr/local/sbin exists
	echo -e "Setting up system based .zshrc..."
	SYSTEM=/usr/local/sbin
	if ! [ -d "$SYSTEM/zsh" ]; then
		echo -e " - Cloning into $SYSTEM/zsh\n"
		clone_repository "$SYSTEM/zsh"
	else
		echo -e " - $SYSTEM/zsh already exists\n"
		exit 1
	fi
	# Uncommented for now, need to review
	#echo -e " - Detecting OS and installing for all system users"
	#if [ -f /etc/debian_version ]; then
	#	echo -e " -- Detected Debian/Ubuntu OS"		
	#fi
	#echo "This is broken and needs to be fixed! and should probably be in /usr/share/zsh?"
	
	echo -e "You can now copy the .zshrc_local to your home directory"
	echo -e "cp $SYSTEM/zsh/.zshrc_install ~/.zshrc"

}		

#--------------------
# Main Code
#--------------------

echo -e " -- Flight Check"
flight_check
echo -e " -- Begin Install"
install_method

if [ $INSTALL = "s" ]; then
        setup_system
elif [ $INSTALL = "h" ]; then
        setup_home
else
        install_method "Choose s or h on your keyboard"
fi

echo -e " -- Installation complete."