# Edit your custom power level 9k
alias jpl="joe $ZSH_CUSTOM/powerlevel9k.zshrc"
# Power Level 9K Customizations
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( status root_indicator context dir )
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( load disk_usage command_execution_time background_jobs history time )
POWERLEVEL9K_DIR_PATH_HIGHLIGHT_FOREGROUND="grey"
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_FOREGROUND="grey"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="grey"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
POWERLEVEL9K_DISK_USAGE_ONLY_WARNING="true"
POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL="90"
POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
